# x=10
# print(x)
try:
  print(x)
except :
  print("An exception occurred")